"""
Run this script ONCE from the folder that contains your image files.
It will generate a file called  images_b64.py  next to this script.
Then place images_b64.py beside Text_to_Speech_Combined.py before building.

Usage:
    python embed_images.py
"""

import base64
import os

images = {
    "MIC_LOGO":    "mic logo.png",
    "TEXT_ICON":   "text icon.png",
    "SPEAK_IMG":   "speak.png",
    "DOWNLOAD_IMG":"download.png",
}

lines = ["# Auto-generated by embed_images.py — do not edit by hand\n"]

for var, filename in images.items():
    if not os.path.exists(filename):
        print(f"[WARNING] '{filename}' not found — skipping.")
        lines.append(f'{var} = None  # "{filename}" was missing during embedding\n')
        continue
    with open(filename, "rb") as f:
        encoded = base64.b64encode(f.read()).decode("utf-8")
    lines.append(f'{var} = "{encoded}"\n')
    print(f"[OK] Embedded '{filename}' as {var}")

with open("images_b64.py", "w") as out:
    out.writelines(lines)

print("\nDone! images_b64.py created.")
print("Place it next to Text_to_Speech_Combined.py and then build with PyInstaller.")
